
2024-06-10 11:42:23,184 Failed
Traceback (most recent call last):
  File "D:\Trung\Project\Checkweigher\Function\Scale.py", line 39, in openPort
    self.scale = Instrument(self.portScale, 1)
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\minimalmodbus.py", line 220, in __init__
    self.serial = _serialports[port] = serial.Serial(
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2024-06-10 11:43:04,596 Failed
Traceback (most recent call last):
  File "D:\Trung\Project\Checkweigher\Function\Scale.py", line 39, in openPort
    self.scale = Instrument(self.portScale, 1)
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\minimalmodbus.py", line 220, in __init__
    self.serial = _serialports[port] = serial.Serial(
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "d:\Trung\software\miniconda\envs\intemtui\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
